config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi|ja/ do
    root "static_pages#home"
  end

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  get "/register", to: "users#register_card"
  patch "/register", to: "users#require_card"

  resources :users
  resources :books do
    resources :comments
    resources :copies, only: %i(index new create update destroy)
  end
  resources :card_activations, only: %i(edit)
  resources :password_resets, only: %i(new create edit update)
  resources :registered_copies, only: %i(index new create update destroy)
  resources :book_confirmations, only: %i(index update destroy)
  resources :comment_confirmations, only: %i(index update destroy)
  resources :notifications, only: %i(index create destroy)
end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_paranoid

  belongs_to :book
  belongs_to :user

  scope :all_comments, ->{order(created_at: :asc)}
  scope :not_confirmed_yet, ->{where accepted: false}
  scope :confirmed, ->{where accepted: true}

  validates :content, presence: true
  paginates_per Settings.OBJECT_PER_PAGE
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_book, only: %i(index create show edit update destroy)
  before_action :find_comment, only: %i(edit update destroy)

  def index
    @comments = @book.comments.confirmed.page(params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.build comment_params
    @comment.book_id = @book.id
    @comment.accepted = true if current_user.librarian? || current_user.admin?

    if @comment.save
      respond_to do |format|
        format.html
        format.js {flash.now[:success] = t(".success_comment")}
      end
    end
  end

  def show; end

  def edit; end

  def update
    if @comment.update_attributes(comment_params)
      respond_to do |format|
        format.html
        format.js {flash.now[:success] = t(".updated")}
      end
    end
  end

  def destroy
    @comment.destroy
    flash[:success] = t ".destroyed"
    redirect_to @book
  end

  private

  def find_book
    @book = Book.find_by id: params[:book_id]
    return if @book
    flash[:warning] = t ".not_found_book"
    redirect_back fallback_location: root_path
  end

  def find_comment
    @comment = Comment.find_by id: params[:id]
    return if @comment
    flash[:warning] = t ".not_found_comment"
    redirect_back fallback_location: root_path
  end

  def comment_params
    params.require(:comment).permit :content
  end
end

app/views/comments/_comment.html.haml
%div(class="record" id="record-#{comment.id}")
  %li
    = gravatar_for comment.user, size: Settings.SIZE_IMAGE_OPTION_SMALL
    %strong= comment.user.name
    %span(class="comment-content-#{comment.id}")
      = comment.content
    %br
    %small.comment-edit-delete
      - if comment.user == current_user
        = link_to t("comments._comment.edit"),
          edit_book_comment_path(@book, comment),
          remote: true
        = link_to t("comments._comment.delete"),
          [comment.book, comment], method: :delete, remote: true,
          data: {confirm: t("comments._comment.sure")}
        = t("comments._comment.submitted",
          s: time_ago_in_words(comment.created_at))

app/views/comments/_comment_form.html.haml
= form_for [@book, Comment.new], class: "comment-form",remote: true do |f|
  .comment-form-submit
    = f.submit t("books._comment_form.comment"), class: "btn btn-primary"
  .comment-form-text
    = f.text_area :content, class: "form-control"

app/views/comments/_edit_form.html.haml
#edit-comment-form
  = form_for [@book, @comment], remote: true do |f|
    = f.text_field :content, class: "form-control"

app/views/comments/create.js.erb
$('.comments').prepend('<%= j render @comment %>');
$('#comment_content').val('');
$("#flash").html('<%= j render partial: "flash_messages", flash: flash %>');

app/views/comments/edit.js.erb
$('#record-<%= @comment.id %>').append('<%= j render "edit_form" %>');
$("#flash").html('<%= j render partial: "flash_messages", flash: flash %>');

app/views/comments/index.js.erb
$('.comments').append('<%= j render @comments %>');
$('#load-more-button').attr('href','<%= book_comments_path(@book.id, 
  page: params[:page].to_i + 1) %>')
  

app/views/comments/update.js.erb
$('.comment-content-<%= @comment.id %>').text('<%= @comment.content %>');
$('#edit-comment-form').remove();