config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi|ja/ do
    root "static_pages#home"
  end

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  get "/register", to: "users#register_card"
  patch "/register", to: "users#require_card"

  resources :users
  resources :books do
    resources :comments
    resources :copies, only: %i(index new create update destroy)
  end
  resources :card_activations, only: %i(edit)
  resources :password_resets, only: %i(new create edit update)
  resources :registered_copies, only: %i(index new create update destroy)
  resources :book_confirmations, only: %i(index update destroy)
  resources :comment_confirmations, only: %i(index update destroy)
  resources :notifications, only: %i(index create destroy)
end

app/models/copy.rb
class Copy < ApplicationRecord
  enum status: {available: 0, registered: 1, borrowed: 2}

  has_one :registered_copy
  has_many :cards, through: :registered_copies
  belongs_to :book

  scope :available_copies, ->{where status: :available}

  delegate :title, to: :book, prefix: true, allow_nil: true

  paginates_per Settings.BOOK_PER_PAGE

  def set_status new_status
    update_attributes status: new_status
  end

  def registering_user
    return if available?
    registered_copy.card.user
  end
end

app/controllers/copies_controller.rb
class CopiesController < ApplicationController
  before_action :librarian_user, only: %i(new create update destroy)
  before_action :find_copy, only: %i(update destroy)
  before_action :copy_support, only: %i(new create)

  def index
    @book = Book.find(params[:book_id])
    @copies = @book.copies.page(params[:page])
    return if @copies
    flash[:warning] = t ".not_exists"
    redirect_to root_url
  end

  def new
    @copy = Copy.new
  end

  def create
    @copy = Copy.new copy_params
    if @copy.save
      flash[:info] = t ".success"
      add_notification_current_user t(".notification_copy_created",
        title: @copy.book_title, copy_id: @copy.id),
        Book.name, @copy.book_id
      redirect_to root_url
    else
      render :new
    end
  end

  def update; end

  def destroy
    @copy.destroy
    flash[:success] = t ".copy_deleted"
    redirect_to books_url
  end

  private

  def copy_params
    params.require(:copy).permit :book_id, :status
  end

  def librarian_user
    redirect_to root_url unless current_user.librarian?
  end

  def find_copy
    @copy = Copy.find_by id: params[:id]
    return if @copy
    flash[:warning] = t ".not_exists"
    redirect_to root_url
  end

  def copy_support
    @copy_support = Supports::CopySupport.new
  end
end

app/views/copies/_form.html.haml
= form_for [:book, @copy] do |f|
  = render "shared/error_messages", object: f.object

  = f.label :book
  = f.collection_select :book_id, @copy_support.books,
    :id, :title, include_blank: false
  = f.submit yield(:button_text), class: "btn btn-primary"

  = t ".new_book_message"
  = link_to t(".create_new_book"), new_book_path

app/views/copies/index.html.haml
= provide :title, t(".page_title", book: @book.title)
%h1= t(".page_title", book: @book.title)
%div
  .add-new-book
    - if user_signed_in? && current_user.librarian?
      .button-add-new-book
        = link_to t(".add_copy"), new_book_copy_path, class: "btn btn-primary"

  = paginate @copies, theme: "twitter-bootstrap-4",
    pagination_class: "pagination-sm"

  %h3= t(".available_count", count: @book.copies_available_count)

  = table_for @copies,
  table_html: {class: "table table-bordered", cellpadding: 2},
  header: lambda {|column| t("tables.headers.#{column.name.to_s.underscore}",
  default: column.name.to_s.titleize)} do |table|
    - table.column :id
    - table.column :status
    - table.column header: t(".user") do |copy|
      - if copy.registered_copy.present?
        = link_to "#{copy.registering_user.name}",
          user_path(id: copy.registering_user.id)
    - if current_user.librarian?
      - table.column header: false do |copy|
        = link_to t(".delete"), [@book, copy], method: :delete,
          data: {confirm: t(".confirm")}

  #back_to_top.active
    %i(class="fa fa-angle-up" aria-hidden="true")

app/views/copies/new.html.haml
= provide :title, t(".page_title")
= provide :button_text, t(".add_button")
%h1= t ".page_title"
.row
  %div(class="col-md-6 col-md-offset-3")
    = render "form"