config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi|ja/ do
    root "static_pages#home"
  end

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  get "/register", to: "users#register_card"
  patch "/register", to: "users#require_card"

  resources :users
  resources :books do
    resources :comments
    resources :copies, only: %i(index new create update destroy)
  end
  resources :card_activations, only: %i(edit)
  resources :password_resets, only: %i(new create edit update)
  resources :registered_copies, only: %i(index new create update destroy)
  resources :book_confirmations, only: %i(index update destroy)
  resources :comment_confirmations, only: %i(index update destroy)
  resources :notifications, only: %i(index create destroy)
end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      = t("shared._error_messages.headf", 
        s: pluralize(object.errors.count, 
        t("shared._error_messages.error")))
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_homepage.html.haml
= provide :title, t("shared.homepage.page_title")
.banner
  .container-xs
    %h1.text-white= t "shared.homepage.welcome_message"
    %h3.text-white.banner-xs= t "shared.homepage.quote"
    %div.rh.form-search
      .container
        .comment-form-x
          = form_tag books_path, method: :get do
            .comment-form-submit-home
              = image_submit_tag Settings.IMAGE_SEARCH, class: "btn btn-primary", title: t(".search")
            .comment-form-text-home
              = text_field_tag :search, params[:search],
                class: "form-control", placeholder: t(".type_book_title")