config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  scope "(:locale)", locale: /en|vi|ja/ do
    root "static_pages#home"
  end

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"

  get "/register", to: "users#register_card"
  patch "/register", to: "users#require_card"

  resources :users
  resources :books do
    resources :comments
    resources :copies, only: %i(index new create update destroy)
  end
  resources :card_activations, only: %i(edit)
  resources :password_resets, only: %i(new create edit update)
  resources :registered_copies, only: %i(index new create update destroy)
  resources :book_confirmations, only: %i(index update destroy)
  resources :comment_confirmations, only: %i(index update destroy)
  resources :notifications, only: %i(index create destroy)
end

app/controllers/book_confirmations_controller.rb
class BookConfirmationsController < ApplicationController
  before_action :has_book_pending?, only: %i(index)
  before_action :find_registered_copy, only: %i(update destroy)

  def index; end

  def update
    if @book_confirmation.update_attributes(borrowed: true)
      set_borrowed
      add_book_duration
      add_notification_user(@book_confirmation.card.user_id,
        t(".noti_book_confirmed", title: @book_confirmation.copy.book_title),
        Book.name, @book_confirmation.copy.book_id)
      flash[:success] = t ".updated"
    else
      flash[:warning] = t ".failed"
    end
    redirect_to root_url
  end

  def destroy
    return unless set_available
    @book_confirmation.destroy
    add_notification_user(@book_confirmation.card.user_id,
      t(".noti_book_not_confirmed", title: @book_confirmation.copy.book_title),
      Book.name, @book_confirmation.copy.book_id)
    flash[:success] = t ".not_confirm"
    redirect_back fallback_location: root_path
  end

  private

  def has_book_pending?
    @book_confirmations = RegisteredCopy.page(params[:page]).not_confirmed_yet
    return if @book_confirmations.present?
    flash[:info] = t ".no_book_pending_right_now"
    redirect_to root_url
  end

  def find_registered_copy
    @book_confirmation = RegisteredCopy.find_by id: params[:id]
    return if @book_confirmation
    flash[:warning] = t ".not_exists"
    redirect_to root_url
  end

  def add_book_duration
    @book_confirmation.update_attributes(borrowed_date: Date.today,
      expected_return_date: Settings.EXPIRED_WEEK.weeks.from_now.to_date)
  end

  def set_available
    @copy = Copy.find_by id: @book_confirmation.copy_id
    return if !@copy || @copy.available?
    @copy.set_status :available
  end

  def set_borrowed
    @copy = Copy.find_by id: @book_confirmation.copy_id
    return if !@copy || @copy.borrowed?
    @copy.set_status :borrowed
  end
end

app/views/book_confirmations/index.html.haml
= provide :title, t(".page_title")
.text-center
  %h1= t ".page_title"
  %div
    = paginate @book_confirmations, theme: "twitter-bootstrap-4",
      pagination_class: "pagination-sm"
  %br

.container
  = table_for @book_confirmations,
    table_html: {class: "table table-bordered", cellpadding: 2},
    header: lambda {|column| t("tables.headers.#{column.name.to_s.underscore}",
    default: column.name.to_s.titleize)} do |table|
    - table.column :card_id do |book_confirmation|
      = link_to "#{book_confirmation.card.user_name}",
        user_path(id: book_confirmation.card.user_id)
    - table.column :copy_id do |book_confirmation|
      = link_to "#{book_confirmation.copy.book_title}",
        book_path(id: book_confirmation.copy.book_id)
    - table.column :registered_date
    - table.column header: false do |book_confirmation|
      = link_to t(".confirm"), book_confirmation_path(book_confirmation),
        method: :put, data: {confirm: t(".confirm_text")}
    - table.column header: false do |book_confirmation|
      = link_to t(".delete"), book_confirmation_path(book_confirmation),
        method: :delete, data: {confirm: t(".confirm_delete")}